apiVersion: v1
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://db:5432/testdb
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: order-microservice-config