apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice
  labels:
    app: order-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
        - name: order-microservice
          image: swapnadocker146/microservicedocker-order-microservice:latest
          ports:
            - containerPort: 8082