apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentgateway-microservice
  labels:
    app: studentgateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentgateway-microservice
  template:
    metadata:
      labels:
        app: studentgateway-microservice
    spec:
      containers:
        - name: studentgateway-microservice
          image: swapnadocker146/microservicedocker-studentgateway-microservice:latest
          ports:
            - containerPort: 9090