apiVersion: v1
kind: ConfigMap
metadata:
  name: student-microservice-config
data:
  application.yml: |
    server:
      port: 8081

    spring:
      datasource:
        url: jdbc:postgresql://db:5432/testdb
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: update