apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: student-microservice
  name: student-microservice

spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-microservice

  template:
    metadata:
      labels:
        app: student-microservice

    spec:
      containers:
        - name: student-microservice
          image: swapnadocker146/microservicedocker-student-microservice:latest
          ports:
            - containerPort: 8081

          volumeMounts:
            - name: config
              mountPath: /config

      volumes:
        - name: config
          configMap:
            name: student-microservice-config